Invoked as 'test.doctests.py' on Saturday, 22 December 2018 at 9:36:14 PM.
Initializing ...
teneya error: data.in: file not found.
