Invoked as 'test.doctests.py' on Sunday, 15 July 2018 at 1:05:49 AM.
Initializing ...
teneya error: data.in: file not found.
